services:
  - type: web
    name: healthcare-translation-app
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
    buildFilter:
      paths:
      - requirements.txt
      - "**/*.py"