services:
  - type: web
    name: your-app-name
    env: python
    buildCommand: apt-get update && apt-get install -y portaudio19-dev python3-all-dev && pip install -r requirements.txt
    startCommand: unvicorn main:app  # Replace with your actual start command